# Generated by Django 4.1.6 on 2023-07-21 11:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kiyafet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255)),
                ('satici', models.CharField(max_length=255)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('fiyat', models.IntegerField(default=0)),
                ('imgUrl', models.URLField(default='https://cdn.dsmcdn.com/ty965/product/media/images/20230712/14/393134474/934329462/2/2_org.jpg')),
            ],
        ),
        migrations.CreateModel(
            name='Puan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degerlendirme', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Kiyafet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Puanlar', to='Kiyafetler.Kiyafet')),
            ],
        ),
    ]
