# Generated by Django 4.1.6 on 2023-07-21 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiyafetler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puan',
            name='Puan_sahibi',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='Puan_sahibi', to=settings.AUTH_USER_MODEL),
        ),
    ]
